
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sounds_development

  username: emmanueldev
  password: nazgul666

  host: localhost
  port: 5432

test:
  <<: *default
  database: sounds_test
  username: emmanueldev
  password: nazgul666

  host: localhost
  port: 5432
  
production:
  <<: *default
  database: sounds_production
  username: sounds
  password: <%= ENV['SOUNDS_DATABASE_PASSWORD'] %>
